shipping_project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'home#index'

	patch 'user_path' => 'users#avatar', as: "user"

	patch 'jobs/:job_id/add_boat' => 'jobs#add_boat', as: "add_boat"

	get '/users' => 'users#index'


	resources :boats
	resources :locations
	resources :jobs


	patch 'boats/:boat/remove_job/:job_id' => 'boats#remove_job'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

shipping_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shipping_project/app/models/boat.rb
class Boat < ActiveRecord::Base
	has_and_belongs_to_many :jobs
	belongs_to :location
	belongs_to :user

	validates :name, presence: true, uniqueness: true
	validates :containers, presence: true, numericality: true

    has_attached_file :avatar, :styles => 
	  	{ :medium => "300x300>", :thumb => "100x100>" }, 
	  	:default_url => "/images/:style/missing.png" 
  
	validates_attachment_content_type :avatar, 
  		:content_type => /\Aimage\/.*\Z/
end

shipping_project/app/models/job.rb
class Job < ActiveRecord::Base
	has_and_belongs_to_many :boats
	belongs_to :origin, class_name: 'Location', foreign_key: 'origin_id'
	belongs_to :destination, class_name: 'Location', foreign_key: 'destination_id'
	belongs_to :user

	validates :description, presence: true, length: {minimum: 50, maximum: 255}
	validates :cost, presence: true, numericality: { greater_than: 999 }
	validates :containers_needed, presence: true, numericality: true

	def containers_assigned
		result = 0
		self.boats.all.each do |b|
			result += b.containers
		end	
		result
	end



end

shipping_project/app/models/location.rb
class Location < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_many :boats
	has_many :jobs_originating, class_name: 'Job'
	has_many :jobs_destined, class_name: 'Job'
end

shipping_project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :boats
  has_many :jobs

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_attached_file :avatar, :styles => 
  	{ :medium => "300x300>", :thumb => "100x100>" }, 
  	:default_url => "/images/:style/missing.png" 
  
  validates_attachment_content_type :avatar, 
  	:content_type => /\Aimage\/.*\Z/
end

shipping_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

shipping_project/app/controllers/boats_controller.rb
class BoatsController < ApplicationController

	def create
		@boat = Boat.new(boat_params)
		if @boat.save
			redirect_to :back, notice: "Wooh! Boat is afloat!"
		else
			render "home/index", alert: "Boat problem!"
		end
	end

	def remove_job
		@boat = Boat.find params[:boat]
		@job = Job.find params[:job_id]

		@boat.jobs.delete @job
	end



	private
		def boat_params
  			params.require(:boat).permit(:name,:containers,:location,:location_id, :user_id, :avatar)
		end



end

shipping_project/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@boat = Boat.new
		@location = Location.new
		@job = Job.new
	end



	private
		def boat_params
  			params.require(:boat).permit(:name,:containers,:location)
		end
end

shipping_project/app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
	end

	def create
		@job = Job.new(job_params)
		if @job.save
			redirect_to :back, notice: "Wooh! Job is afloat!"
		else
			render "home/index", alert: "Job problem!"
		end
	end

	def update
		@job = Job.find params[:job][:id]


		if @job.update(job_params)
			redirect_to :back, notice: "Job updated"
		else
			render "home/index", alert: "Update failed"
		end
	end

	def add_boat
		@job = Job.find params[:job_id]
		@boat = Boat.find params[:job][:boats]

		@job.boats.append @boat

		render partial: @boat, locals: { job_id: params[:job_id]}
	end

	private

		def job_params
  			params.require(:job).permit(:description,:cost,:containers_needed,:origin_id, :destination_id, :user_id, :boats)
  		end
end

shipping_project/app/controllers/locations_controller.rb
class LocationsController < ApplicationController

	def create
		@location = Location.new(name: params[:location][:name])
		if @location.save
			redirect_to :back, notice: "Wooh! Location is afloat!"
		else
			render "home/index", alert: "Location problem!"
		end
	end
end

shipping_project/app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
end

def avatar
	current_user.avatar = params[:user][:avatar]
	current_user.save!
	redirect_to edit_user_registration_path
end

end

shipping_project/app/helpers/application_helper.rb
module ApplicationHelper
end

shipping_project/app/views/boats/_boat.html.erb
<div>
	<%= image_tag @boat.avatar.url(:thumb) %>
	<p><%= boat.name %></p>
	<p>Containers: <%= boat.containers %></p>


	<%= link_to(
		"Remove Boat from Job",	{
			controller: "boats",
			boat: boat,
			action: "remove_job",
			job_id: job_id,
			remote: true,
		}, {
			method: :patch,
			class: "remove-association"
		}, 
	) %>
</div>

shipping_project/app/views/home/_boat_form.html.erb
<h2 style="color: blue;">Register a boat</h2>
<%= form_for @boat, :html => { :multipart => true } do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %><br/>
	<%= f.label :containers %>:
	<%= f.text_field :containers %><br/>
	<%= f.label :location_id %>:
	<%= f.select :location_id , Location.all.map {|r| [ r.name, r.id ] }, { :include_blank => true } %>
	<br/>
	<%= f.label :avatar %>
	<%= f.file_field :avatar %>

	<%= f.hidden_field :user_id, value: current_user.id %>

	<%= f.submit %>
<% end %>

shipping_project/app/views/home/_job_form.html.erb
<h2 style="color: blue;">Register a job</h2>
<%= form_for @job do |f| %>
	<%= f.label :description %>:
	<%= f.text_area :description %><br/>
	<%= f.label :cost %>:
	<%= f.text_field :cost %><br/>
	<%= f.label :containers_needed %>:
	<%= f.text_field :containers_needed %><br/>
	<%= f.label :origin_id %>:
	<%= f.select :origin_id , Location.all.map {|r| [ r.name, r.id ] }, { :include_blank => true } %>
	<%= f.label :destination_id %>:
	<%= f.select :destination_id , Location.all.map {|r| [ r.name, r.id ] }, { :include_blank => true } %>
	<br/>
	<%= f.hidden_field :user_id, value: current_user.id %>

	<%= f.submit %>
<% end %>

shipping_project/app/views/home/_location_form.html.erb
<h2 style="color: blue;">Register a location</h2>
<%= form_for @location do |f| %>
	<%= f.label :name %>:
	<%= f.text_field :name %><br/>
	<%= f.submit %>
<% end %>

shipping_project/app/views/home/index.html.erb
<%= render 'boat_form' %>
<%= render 'location_form' %>
<%= render 'job_form' %>

<h2>My Jobs</h2>
<% current_user.jobs.each do |j| %>
	<div style="border: 1px solid black">
		<p>Job Description: <%= j.description %></p>
		<p>Projected Cost: <%= j.cost %></p>
		<p>Containers Needed: <%= j.containers_needed %></p>
		<p>Containers Assigned: <%= j.containers_assigned %></p>
		<p>From: <%= j.origin.name %> To: <%= j.destination.name %></p>
		<div class="boat-list">
			<%= form_for j, remote: true, url: add_boat_path(j.id) do |f| %>
				<%= f.label :boats %>:
				<%= f.select :boats, current_user.boats.all.map {|r| [ r.name, r.id ] }, { :include_blank => true } %>
				<%= f.submit "Add Boat" %>

			<% end %>			
			<p>Boats assigned:</p>
			<%= render partial: j.boats, locals: {job_id: j.id} %>

		</div>



		
	</div>
<% end %>

shipping_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShippingProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h2><%= link_to "Shipping Manager Pro", root_path %></h2>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  	<% if user_signed_in? %>
	    <%= link_to 'Sign out',  destroy_user_session_path,  method: :delete, data: { confirm: 'Are you sure?' } %>
	    <%= image_tag current_user.avatar.url(:thumb) %>
      <%= link_to "Users", users_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

shipping_project/app/views/users/index.html.erb
<% User.all.each do |u| %>
	<h1><%= u.email %></h1>
	<%= image_tag u.avatar.url(:medium) %>
	<ul>
		<% u.boats.each do |b| %>
			<li>
				<%= b.name %>
				<%= image_tag b.avatar.url(:thumb) %>
			</li>
		<% end %>
	</ul>
<% end %>